# Generated by Django 4.2.30 on 2026-09-17 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('subcategory', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('subcategory', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('statya', models.CharField(blank=True, max_length=255, verbose_name='Статья')),
                ('rod_statya', models.CharField(blank=True, max_length=255, verbose_name='Род. статья')),
                ('direction', models.CharField(blank=True, max_length=255, verbose_name='Направление')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('source', models.CharField(choices=[('excel', 'Загрузка Excel'), ('fintablo_api', 'API Финтабло')], default='excel', max_length=20)),
                ('external_id', models.CharField(blank=True, help_text='ID операции в источнике (для API Финтабло) — чтобы не задваивать при повторной синхронизации', max_length=255, null=True, unique=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlanEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('subcategory', models.CharField(blank=True, default='', max_length=255)),
                ('direction', models.CharField(blank=True, default='', max_length=255)),
                ('week_start', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
        ),
        migrations.AddConstraint(
            model_name='planentry',
            constraint=models.UniqueConstraint(fields=('group', 'category', 'subcategory', 'direction', 'week_start'), name='unique_plan_entry'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['date'], name='finance_ope_date_7a3aa4_idx'),
        ),
        migrations.AddField(
            model_name='expenseoverride',
            name='operation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expense_override', to='finance.operation'),
        ),
        migrations.AddField(
            model_name='categoryoverride',
            name='operation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='category_override', to='finance.operation'),
        ),
    ]
