# Generated by Django 4.2.30 on 2026-09-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeMonthlyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('direction', models.CharField(blank=True, default='', max_length=255)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='IncomePlanEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('direction', models.CharField(blank=True, default='', max_length=255)),
                ('week_start', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeWeekendFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, unique=True)),
                ('works_weekends', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddConstraint(
            model_name='incomeplanentry',
            constraint=models.UniqueConstraint(fields=('category', 'direction', 'week_start'), name='unique_income_plan_entry'),
        ),
        migrations.AddConstraint(
            model_name='incomemonthlyplan',
            constraint=models.UniqueConstraint(fields=('category', 'direction', 'year', 'month'), name='unique_income_monthly_plan'),
        ),
    ]
