# Generated by Django 4.2.30 on 2026-09-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_incomemonthlyplan_incomeplanentry_incomeweekendflag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeweekendflag',
            name='direction',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='incomeweekendflag',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='incomeweekendflag',
            constraint=models.UniqueConstraint(fields=('category', 'direction'), name='unique_income_weekend_flag'),
        ),
    ]
