# Generated by Django 4.2.30 on 2026-09-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_incomeweekendflag_direction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeDailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('direction', models.CharField(blank=True, default='', max_length=255)),
                ('day', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
        ),
        migrations.AddConstraint(
            model_name='incomedailyplan',
            constraint=models.UniqueConstraint(fields=('category', 'direction', 'day'), name='unique_income_daily_plan'),
        ),
    ]
