# Generated by Django 4.2.30 on 2026-09-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_incomedailyplan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseDailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('subcategory', models.CharField(blank=True, default='', max_length=255)),
                ('direction', models.CharField(blank=True, default='', max_length=255)),
                ('day', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
        ),
        migrations.AddConstraint(
            model_name='expensedailyplan',
            constraint=models.UniqueConstraint(fields=('group', 'category', 'subcategory', 'direction', 'day'), name='unique_expense_daily_plan'),
        ),
    ]
