# Generated by Django 4.2.30 on 2026-09-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_expensedailyplan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseMonthlyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('subcategory', models.CharField(blank=True, default='', max_length=255)),
                ('direction', models.CharField(blank=True, default='', max_length=255)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
        ),
        migrations.AddConstraint(
            model_name='expensemonthlyplan',
            constraint=models.UniqueConstraint(fields=('group', 'category', 'subcategory', 'direction', 'year', 'month'), name='unique_expense_monthly_plan'),
        ),
    ]
