# Generated by Django 4.2.30 on 2026-09-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_fundtransfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundBalanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fund', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'fund'],
            },
        ),
        migrations.CreateModel(
            name='FundIncomeShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('fund', models.CharField(max_length=255)),
                ('share', models.DecimalField(decimal_places=4, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', '-month', 'fund'],
            },
        ),
        migrations.AddConstraint(
            model_name='fundincomeshare',
            constraint=models.UniqueConstraint(fields=('fund', 'year', 'month'), name='unique_fund_income_share'),
        ),
        migrations.AddConstraint(
            model_name='fundbalancesnapshot',
            constraint=models.UniqueConstraint(fields=('fund', 'date'), name='unique_fund_balance_snapshot'),
        ),
    ]
