"""
Django settings for kiwiweb project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Локальная разработка не требует переменных окружения — значения по
# умолчанию ниже работают "из коробки" на localhost, как и раньше. На
# проде (PythonAnywhere и т.п.) DJANGO_SECRET_KEY/DJANGO_DEBUG/
# DJANGO_ALLOWED_HOSTS задаются через переменные окружения — см. DEPLOY.md.

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-wbb(i*2v9r54^g@lzf707jy4xcwx049n+(8#$sb0_gh$(w^91-",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1,testserver").split(",") if h.strip()
]

# Нужно Django 4+ для POST-форм (план, загрузка) с настоящего домена по
# https — без этого CSRF отклоняет все сохранения на проде. Локально пусто,
# на проде — сам домен (см. DEPLOY.md).
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",") if o.strip()
]

# Только при DEBUG=False (прод) — локально сайт по http, эти флаги сломали
# бы вход. SECURE_SSL_REDIRECT сознательно не трогаем: PythonAnywhere сам
# завершает HTTPS на своём прокси и предлагает свой чекбокс "Force HTTPS" —
# редирект на уровне Django поверх их же прокси рискует зациклиться.
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    # Amvera (и PythonAnywhere) завершают HTTPS на своём прокси и
    # проксируют к gunicorn уже по обычному http — без этой строки Django
    # думает, что соединение небезопасное (request.is_secure() = False),
    # и тогда secure-куки (сессия, CSRF) не работают — именно это ломало
    # вход с "Ошибка проверки CSRF" на Amvera. Безопасно только пока прокси
    # сам подставляет X-Forwarded-Proto и не даёт его подделать снаружи —
    # это так и есть у обеих платформ, поэтому включаем только при
    # DEBUG=False (в проде), не трогая локальный runserver без прокси.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Страница "План" объединяет план расходов (по дням — до ~900 полей на
# одну неделю) и встроенный план поступлений в одной форме — легко
# превышает стандартный лимит Django в 1000 полей на обычных данных, без
# всякой атаки. Поднимаем с запасом на будущий рост числа статей/направлений.
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'finance',
]

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'income'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kiwiweb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kiwiweb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# На Amvera файловая система контейнера пересоздаётся при каждом деплое —
# переживает только persistenceMount (/data, см. amvera.yaml). Поэтому путь
# к db.sqlite3 настраиваемый: DJANGO_DB_PATH задаётся только там, локально
# и на PythonAnywhere её нет — база остаётся в корне проекта, как раньше.

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.environ.get('DJANGO_DB_PATH', str(BASE_DIR / 'db.sqlite3')),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Asia/Almaty'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
# Своих статических файлов у приложения нет (Tailwind/htmx — с CDN), это
# только для /admin/ (django.contrib.admin) — но collectstatic на проде
# всё равно нужен, иначе стили админки не найдутся.

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
